export const WEEKLY_HANDLER = 'WEEKLY_HANDLER';
export const MONTHLY_HANDLER = 'MONTHLY_HANDLER';
export const YEARLY_HANDLER = 'YEARLY_HANDLER';
export const SHOW_SELECT_LIST = 'SHOW_SELECT_LIST';
export const CHOOSE_DATE = 'CHOOSE_DATE'