export const data = {
    
    "months":[
         {
             "short":"Jan",
             "long":"January"
         },
         {
            "short":"Feb",
            "long":"Febrauary"
        },
        {
            "short":"Mar",
            "long":"March"
        },
        {
            "short":"Apr",
            "long":"April"
        },
        {
            "short":"May",
            "long":"May"
        },
        {
            "short":"Jun",
            "long":"June"
        },
        {
            "short":"Jul",
            "long":"July"
        },
        {
            "short":"Aug",
            "long":"August"
        },
        {
            "short":"Sep",
            "long":"September"
        },
        {
            "short":"Oct",
            "long":"October"
        },
        {
            "short":"Nov",
            "long":"November"
        },
        {
            "short":"Dec",
            "long":"December"
        }
    ],
    "years":[
        "2014","2015","2016","2017","2018","2019","2020","2021","2022","2023","2024","2025"
    ]
}